<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251026125020 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE greeting_id_seq CASCADE');
        $this->addSql('CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, username VARCHAR(75) NOT NULL, message TEXT NOT NULL, data JSON DEFAULT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_username ON activity (username)');
        $this->addSql('CREATE INDEX idx_timestamp ON activity (timestamp)');
        $this->addSql('CREATE INDEX idx_type ON activity (type)');
        $this->addSql('CREATE TABLE global_counter (id INT NOT NULL, value INT NOT NULL, total_users INT NOT NULL, active_users INT NOT NULL, last_updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE note (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, user_id VARCHAR(75) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_note_user_id ON note (user_id)');
        $this->addSql('CREATE INDEX idx_note_created_at ON note (created_at)');
        $this->addSql('CREATE TABLE playground_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(75) NOT NULL, token TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expire_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_460D5BCAF85E0677 ON playground_session (username)');
        $this->addSql('CREATE INDEX idx_token ON playground_session (token)');
        $this->addSql('CREATE INDEX idx_expire_at ON playground_session (expire_at)');
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, completed BOOLEAN NOT NULL, user_id VARCHAR(75) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_task_user_id ON task (user_id)');
        $this->addSql('CREATE INDEX idx_task_completed ON task (completed)');
        $this->addSql('CREATE INDEX idx_task_created_at ON task (created_at)');
        $this->addSql('CREATE TABLE user_stats (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(75) NOT NULL, request_made INT NOT NULL, tasks_created INT NOT NULL, tasks_completed INT NOT NULL, notes_created INT NOT NULL, rank VARCHAR(50) NOT NULL, badges JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_activity TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B5859CF2F85E0677 ON user_stats (username)');
        $this->addSql('DROP TABLE greeting');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE greeting_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE greeting (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE global_counter');
        $this->addSql('DROP TABLE note');
        $this->addSql('DROP TABLE playground_session');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE user_stats');
    }
}
