<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251025165130 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        // Create indexes only if they don't exist
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_username ON activity (username)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_timestamp ON activity (timestamp)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_type ON activity (type)');
        
        // Modify global_counter id to be non-auto-increment (singleton pattern)
        $this->addSql('ALTER TABLE global_counter ALTER id TYPE INT');
        $this->addSql('ALTER TABLE global_counter ALTER id DROP IDENTITY');
        
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_user_id ON note (user_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_created_at ON note (created_at)');
        
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_460D5BCAF85E0677 ON playground_session (username)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_token ON playground_session (token)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_expire_at ON playground_session (expire_at)');
        
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_user_id ON task (user_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_completed ON task (completed)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_created_at ON task (created_at)');
        
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_B5859CF2F85E0677 ON user_stats (username)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX UNIQ_460D5BCAF85E0677');
        $this->addSql('DROP INDEX idx_token');
        $this->addSql('DROP INDEX idx_expire_at');
        $this->addSql('DROP INDEX UNIQ_B5859CF2F85E0677');
        $this->addSql('ALTER TABLE global_counter ALTER id TYPE INT');
        $this->addSql('ALTER TABLE global_counter ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('DROP INDEX idx_username');
        $this->addSql('DROP INDEX idx_timestamp');
        $this->addSql('DROP INDEX idx_type');
        $this->addSql('DROP INDEX idx_user_id');
        $this->addSql('DROP INDEX idx_completed');
        $this->addSql('DROP INDEX idx_created_at');
        $this->addSql('DROP INDEX idx_user_id');
        $this->addSql('DROP INDEX idx_created_at');
    }
}
